services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hiroki1564
      POSTGRES_USER: postgres
      POSTGRES_DB: shopify_app
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
